"""SQLModel definitions for Chorus - Task-Centric Claude Session Orchestrator."""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from sqlmodel import Field, SQLModel


class TaskStatus(str, Enum):
    """Task lifecycle status."""
    pending = "pending"      # Task created, not yet started (no tmux, no stack)
    running = "running"      # tmux process active, Claude is working
    waiting = "waiting"      # Claude is asking for permission
    completed = "completed"  # Task finished, changes committed via GitButler
    failed = "failed"        # Task failed or was cancelled


class ClaudeStatus(str, Enum):
    """Claude session status within a task's tmux process."""
    stopped = "stopped"      # Claude not running in tmux (can be restarted)
    starting = "starting"    # Claude is initializing
    idle = "idle"            # Claude at prompt, waiting for input
    busy = "busy"            # Claude is processing
    waiting = "waiting"      # Claude asking for permission


class DocumentCategory(str, Enum):
    """Document category enum."""
    instructions = "instructions"
    plans = "plans"
    communication = "communication"
    context = "context"
    general = "general"


class Task(SQLModel, table=True):
    """A unit of work with its own tmux process and GitButler stack.

    This is the primary entity in Chorus. Each task:
    - Has a UUID that serves triple duty: Task ID, Claude session_id, GitButler session identifier
    - Runs in its own tmux process for isolation
    - Is attached to a GitButler auto-created stack (discovered after first file edit)
    - Can have multiple Claude sessions (restartable with --resume)
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    title: str
    description: str = Field(default="")
    priority: int = Field(default=0)
    status: TaskStatus = Field(default=TaskStatus.pending)

    # GitButler integration (auto-discovered after first file edit)
    stack_cli_id: Optional[str] = Field(default=None)    # CLI ID, e.g., "u0", discovered via hooks
    stack_name: Optional[str] = Field(default=None)      # Auto-created name, e.g., "zl-branch-15"

    # tmux process
    tmux_session: Optional[str] = Field(default=None)  # e.g., "task-{uuid}"

    # Claude session state (ephemeral, can be restarted)
    # Note: task.id (UUID) is used for GitButler hooks (persistent)
    # claude_session_id is used for Claude's --resume (changes on restart)
    claude_session_id: Optional[str] = Field(default=None)  # For --resume, changes on Claude restart
    claude_status: ClaudeStatus = Field(default=ClaudeStatus.stopped)
    claude_restarts: int = Field(default=0)
    last_output: str = Field(default="")  # Last ~2000 chars of terminal output
    permission_prompt: Optional[str] = Field(default=None)

    # Timestamps
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    started_at: Optional[datetime] = Field(default=None)  # When tmux was spawned
    completed_at: Optional[datetime] = Field(default=None)

    # Completion info (commit messages auto-generated by GitButler)
    result: Optional[str] = Field(default=None)  # Completion notes or failure reason


class Document(SQLModel, table=True):
    """A tracked markdown file in the project."""
    id: Optional[int] = Field(default=None, primary_key=True)
    path: str = Field(unique=True)
    category: DocumentCategory = Field(default=DocumentCategory.general)
    description: Optional[str] = Field(default=None)
    pinned: bool = Field(default=False)
    last_modified: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DocumentReference(SQLModel, table=True):
    """A reference to specific lines in a document, linked to a task."""
    id: Optional[int] = Field(default=None, primary_key=True)
    document_id: int = Field(foreign_key="document.id")
    task_id: UUID = Field(foreign_key="task.id")  # References Task.id (UUID)
    start_line: int
    end_line: int
    note: Optional[str] = Field(default=None)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
